version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: fh4_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fh4_telemetry
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  telemetry-worker:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    container_name: fh4_worker
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/fh4_telemetry
      - UDP_PORT=5300
    ports:
      - "5300:5300/udp" #  UDP port for game
    volumes:
      - ./src:/app/src # code in container
    command: python -m src.ingestion.udp_listener

volumes:
  pg_data: